// Entities (Zod schemas + inferred types)
export {
  MemberSchema,
  ExpenseSchema,
  PaymentSchema,
  GroupSchema,
  ActivityActionSchema,
  ActivityEntrySchema,
  GroupExportSchema,
  ReparteixExportV1Schema,
  SyncEnvelopeV1Schema,
  type Member,
  type Expense,
  type Payment,
  type Group,
  type ActivityAction,
  type ActivityEntry,
  type GroupExport,
  type ReparteixExportV1,
  type SyncEnvelopeV1,
} from './entities'

// Domain services (pure functions)
export {
  calculateBalances,
  calculateSettlements,
  naiveSettlements,
  calculateNetting,
  computeSyncMerge,
  generateSalt,
  deriveGroupKey,
  encryptPayload,
  decryptPayload,
  encryptSyncPayload,
  decryptSyncPayload,
  type Balance,
  type Settlement,
  type NettingResult,
  type SyncReport,
  type SyncMergeDecision,
  type EncryptedPayload,
} from './services'
